import { useEffect, useMemo, useRef } from 'react'
import type { HeatResponse } from '../../api/heat'
import { PlaybackControls } from '../../components/animation/PlaybackControls'
import { useAnimationPlayback } from '../../components/animation/useAnimationPlayback'

export function HeatPlayback({ result }: { readonly result: HeatResponse }) {
  const snapshots = result.snapshots; const playback = useAnimationPlayback(snapshots.length, 220); const canvasRef = useRef<HTMLCanvasElement>(null)
  const domain = useMemo(() => { const values = snapshots.flatMap((snapshot) => snapshot.field.flat()); return { min: Math.min(...values), max: Math.max(...values) } }, [snapshots]); const snapshot = snapshots[playback.frame]
  useEffect(() => { if (!snapshot) return; const canvas = canvasRef.current; const rows = snapshot.field.length; const columns = snapshot.field[0]?.length ?? 0; if (!canvas || !rows || !columns) return; canvas.width = columns; canvas.height = rows; const context = canvas.getContext('2d'); if (!context) return; const image = context.createImageData(columns, rows); for (let row = 0; row < rows; row += 1) for (let column = 0; column < columns; column += 1) { const pixel = ((rows - row - 1) * columns + column) * 4; const color = colorFor(snapshot.field[row][column], domain); image.data.set([...color, 255], pixel) } context.putImageData(image, 0, 0) }, [domain, snapshot])
  if (!snapshot) return null
  return <section className="playback-panel"><h3>Diffusion playback</h3><p>Qualitative playback from bounded, spatially downsampled snapshots. The color scale is fixed across all frames.</p>{playback.reducedMotion && <p role="status">Playback is disabled by your reduced-motion preference. You can inspect individual frames.</p>}<canvas ref={canvasRef} className="heat-playback" role="img" aria-label={`Heat diffusion snapshot at ${snapshot.time.toFixed(3)} ${result.units.time}; fixed temperature scale ${domain.min.toFixed(3)} to ${domain.max.toFixed(3)} ${result.units.temperature}`} /><PlaybackControls frame={playback.frame} frameCount={snapshots.length} timeLabel={`t = ${snapshot.time.toFixed(3)} ${result.units.time}`} isPlaying={playback.isPlaying} canPlay={playback.canPlay} speed={playback.speed} onPlay={playback.play} onPause={playback.pause} onReset={playback.reset} onStep={playback.step} onFrame={playback.setFrame} onSpeed={playback.setSpeed} /></section>
}
function colorFor(value: number, domain: { min: number; max: number }): [number, number, number] { const value01 = domain.max === domain.min ? 0.5 : Math.min(1, Math.max(0, (value - domain.min) / (domain.max - domain.min))); const stops: [number, number, number][] = [[11, 41, 64], [0, 153, 177], [255, 213, 79], [238, 91, 59]]; const position = value01 * 3; const lower = Math.floor(position); const upper = Math.ceil(position); return stops[lower].map((channel, index) => Math.round(channel + (stops[upper][index] - channel) * (position - lower))) as [number, number, number] }
