"""Reusable visualization helpers for engineering simulations."""

from visualization.plot_style import (
    DEFAULT_DPI,
    DEFAULT_LINE_WIDTH,
    DIVERGING_COLORMAP,
    ENGINEERING_COLOR_CYCLE,
    THERMAL_COLORMAP,
    WAVE_COLORMAP,
    WAVE_DIVERGING_COLORMAP,
    add_clean_colorbar,
    add_colorbar,
    apply_engineering_plot_style,
    apply_plot_style,
    create_streamlit_figure,
    create_streamlit_subplots,
    display_streamlit_figure,
    ensure_readable_axes,
    finalize_streamlit_figure,
    format_axes,
    format_engineering_axes,
    format_heatmap_axes,
    place_legends_outside,
    place_legend_outside,
    save_figure,
    set_equal_2d_axes,
    set_xy_plot_limits_with_margin,
    symmetric_color_limits,
)

__all__ = [
    "DEFAULT_DPI",
    "DEFAULT_LINE_WIDTH",
    "DIVERGING_COLORMAP",
    "ENGINEERING_COLOR_CYCLE",
    "THERMAL_COLORMAP",
    "WAVE_COLORMAP",
    "WAVE_DIVERGING_COLORMAP",
    "add_colorbar",
    "add_clean_colorbar",
    "apply_engineering_plot_style",
    "apply_plot_style",
    "create_streamlit_figure",
    "create_streamlit_subplots",
    "display_streamlit_figure",
    "ensure_readable_axes",
    "format_axes",
    "format_engineering_axes",
    "format_heatmap_axes",
    "finalize_streamlit_figure",
    "place_legends_outside",
    "place_legend_outside",
    "save_figure",
    "set_equal_2d_axes",
    "set_xy_plot_limits_with_margin",
    "symmetric_color_limits",
]
